//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA.OnlineStore.DataAccess.ServiceReferenceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWCF.INewWebService")]
    public interface INewWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewWebService/GetPublicityList", ReplyAction="http://tempuri.org/INewWebService/GetPublicityListResponse")]
        SA.OnlineStore.WCF.PublicityService[] GetPublicityList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewWebService/GetPublicityList", ReplyAction="http://tempuri.org/INewWebService/GetPublicityListResponse")]
        System.Threading.Tasks.Task<SA.OnlineStore.WCF.PublicityService[]> GetPublicityListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewWebServiceChannel : SA.OnlineStore.DataAccess.ServiceReferenceWCF.INewWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewWebServiceClient : System.ServiceModel.ClientBase<SA.OnlineStore.DataAccess.ServiceReferenceWCF.INewWebService>, SA.OnlineStore.DataAccess.ServiceReferenceWCF.INewWebService {
        
        public NewWebServiceClient() {
        }
        
        public NewWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SA.OnlineStore.WCF.PublicityService[] GetPublicityList() {
            return base.Channel.GetPublicityList();
        }
        
        public System.Threading.Tasks.Task<SA.OnlineStore.WCF.PublicityService[]> GetPublicityListAsync() {
            return base.Channel.GetPublicityListAsync();
        }
    }
}
