//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA.OnlineStore.DataAccess.FirstWebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publicity", Namespace="http://schemas.datacontract.org/2004/07/SA.OnlineStore.WCF")]
    [System.SerializableAttribute()]
    public partial class Publicity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FirstWebServiceReference.IFirstWebService")]
    public interface IFirstWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/Message", ReplyAction="http://tempuri.org/IFirstWebService/MessageResponse")]
        string Message();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/Message", ReplyAction="http://tempuri.org/IFirstWebService/MessageResponse")]
        System.Threading.Tasks.Task<string> MessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/add", ReplyAction="http://tempuri.org/IFirstWebService/addResponse")]
        int add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/add", ReplyAction="http://tempuri.org/IFirstWebService/addResponse")]
        System.Threading.Tasks.Task<int> addAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/GetPublicity", ReplyAction="http://tempuri.org/IFirstWebService/GetPublicityResponse")]
        SA.OnlineStore.DataAccess.FirstWebServiceReference.Publicity GetPublicity(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/GetPublicity", ReplyAction="http://tempuri.org/IFirstWebService/GetPublicityResponse")]
        System.Threading.Tasks.Task<SA.OnlineStore.DataAccess.FirstWebServiceReference.Publicity> GetPublicityAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/GetPublicityList", ReplyAction="http://tempuri.org/IFirstWebService/GetPublicityListResponse")]
        SA.OnlineStore.DataAccess.FirstWebServiceReference.Publicity[] GetPublicityList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/GetPublicityList", ReplyAction="http://tempuri.org/IFirstWebService/GetPublicityListResponse")]
        System.Threading.Tasks.Task<SA.OnlineStore.DataAccess.FirstWebServiceReference.Publicity[]> GetPublicityListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFirstWebServiceChannel : SA.OnlineStore.DataAccess.FirstWebServiceReference.IFirstWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirstWebServiceClient : System.ServiceModel.ClientBase<SA.OnlineStore.DataAccess.FirstWebServiceReference.IFirstWebService>, SA.OnlineStore.DataAccess.FirstWebServiceReference.IFirstWebService {
        
        public FirstWebServiceClient() {
        }
        
        public FirstWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FirstWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Message() {
            return base.Channel.Message();
        }
        
        public System.Threading.Tasks.Task<string> MessageAsync() {
            return base.Channel.MessageAsync();
        }
        
        public int add(int x, int y) {
            return base.Channel.add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> addAsync(int x, int y) {
            return base.Channel.addAsync(x, y);
        }
        
        public SA.OnlineStore.DataAccess.FirstWebServiceReference.Publicity GetPublicity(int id) {
            return base.Channel.GetPublicity(id);
        }
        
        public System.Threading.Tasks.Task<SA.OnlineStore.DataAccess.FirstWebServiceReference.Publicity> GetPublicityAsync(int id) {
            return base.Channel.GetPublicityAsync(id);
        }
        
        public SA.OnlineStore.DataAccess.FirstWebServiceReference.Publicity[] GetPublicityList() {
            return base.Channel.GetPublicityList();
        }
        
        public System.Threading.Tasks.Task<SA.OnlineStore.DataAccess.FirstWebServiceReference.Publicity[]> GetPublicityListAsync() {
            return base.Channel.GetPublicityListAsync();
        }
    }
}
