//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA.OnlineStore.DataAccess.NewServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publicity", Namespace="http://schemas.datacontract.org/2004/07/SA.OnlineStore.WCF")]
    [System.SerializableAttribute()]
    public partial class Publicity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewServiceReference.INewWebService")]
    public interface INewWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewWebService/GetPublicityList", ReplyAction="http://tempuri.org/INewWebService/GetPublicityListResponse")]
        SA.OnlineStore.DataAccess.NewServiceReference.Publicity[] GetPublicityList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewWebService/GetPublicityList", ReplyAction="http://tempuri.org/INewWebService/GetPublicityListResponse")]
        System.Threading.Tasks.Task<SA.OnlineStore.DataAccess.NewServiceReference.Publicity[]> GetPublicityListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewWebServiceChannel : SA.OnlineStore.DataAccess.NewServiceReference.INewWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewWebServiceClient : System.ServiceModel.ClientBase<SA.OnlineStore.DataAccess.NewServiceReference.INewWebService>, SA.OnlineStore.DataAccess.NewServiceReference.INewWebService {
        
        public NewWebServiceClient() {
        }
        
        public NewWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SA.OnlineStore.DataAccess.NewServiceReference.Publicity[] GetPublicityList() {
            return base.Channel.GetPublicityList();
        }
        
        public System.Threading.Tasks.Task<SA.OnlineStore.DataAccess.NewServiceReference.Publicity[]> GetPublicityListAsync() {
            return base.Channel.GetPublicityListAsync();
        }
    }
}
